parameters:
  PagePagination:
    description: default parameter for pagination page
    name: page
    in: query
    type: integer
    default: 1
  LimitPagination:
    description: default parameter for limit pagination
    name: limit
    in: query
    type: integer
    default: 10
  OrderPagination:
    description: default parameter for order pagination
    name: order_by
    in: query
    type: string
    default: 'created_at'
  SortPagination:
    description: default parameter for sort pagination
    name: sort_by
    in: query
    type: string
    enum: [asc, desc]
    default: 'desc'
  IncludeDeletedData:
    description: flag for identify include deleted data or not
    name: include_deleted_data
    in: query
    type: string
    enum: ['true', 'false']
    default: 'false'
