swagger: '2.0'
info:
  version: '1.0.0'
  title: Test Biofarma
schemes: [http]
consumes: [application/json, multipart/form-data]
produces: [application/json]
securityDefinitions:
  authorization:
    type: apiKey
    in: header
    name: Authorization

paths:
  # health
  /health:
    $ref: ./path/v1/health/health.yml

  # home
  /v1/home:
    $ref: ./path/v1/home/home.yml

  /v1/home/{home_id}:
    $ref: ./path/v1/home/home.id.yml

definitions:
  Home:
    allOf:
      - $ref: "./../common/definitions.yml#/definitions/ModelIdentifier"
      - $ref: "./definitions/home.yml#/definitions/HomeData"
      - $ref: "./../common/definitions.yml#/definitions/ModelTrackTime"