consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    version: 1.0.0
    title: Test Biofarma
paths:
    /health:
        get:
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
    /v1/home:
        get:
            operationId: FindAllPaginationHome
            parameters:
                - enum:
                    - "true"
                    - "false"
                  type: string
                  default: "false"
                  description: flag for identify include deleted data or not
                  name: include_deleted_data
                  in: query
                - type: integer
                  default: !!float 1
                  description: default parameter for pagination page
                  name: page
                  in: query
                - name: limit
                  in: query
                  type: integer
                  default: !!float 10
                  description: default parameter for limit pagination
                - type: string
                  default: created_at
                  description: default parameter for order pagination
                  name: order_by
                  in: query
                - enum:
                    - asc
                    - desc
                  type: string
                  default: desc
                  description: default parameter for sort pagination
                  name: sort_by
                  in: query
            responses:
                "200":
                    description: Success get data
                    schema:
                        $ref: '#/definitions/successFindAllPagination'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Find all home data with pagination
            tags:
                - home
            summary: Find All Pagination
        post:
            security: []
            description: Create new home data
            tags:
                - home
            summary: Create
            operationId: createHome
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createHomeParamsBody'
            responses:
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreate'
    /v1/home/{home_id}:
        get:
            security: []
            description: Find one home data
            tags:
                - home
            summary: Find One
            operationId: FindOneHome
            parameters:
                - required: true
                  type: integer
                  format: uint64
                  name: home_id
                  in: path
                - default: "false"
                  description: flag for identify include deleted data or not
                  name: include_deleted_data
                  in: query
                  enum:
                    - "true"
                    - "false"
                  type: string
            responses:
                "200":
                    schema:
                        $ref: '#/definitions/successFindOne'
                    description: Success get data
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
        put:
            description: Update home data
            tags:
                - home
            summary: Update
            operationId: UpdateHome
            parameters:
                - type: integer
                  format: uint64
                  name: home_id
                  in: path
                  required: true
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/updateHomeParamsBody'
            responses:
                "200":
                    description: Success update
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
        delete:
            parameters:
                - type: integer
                  format: uint64
                  name: home_id
                  in: path
                  required: true
            responses:
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
                "200":
                    description: Success delete data
                    schema:
                        $ref: '#/definitions/success'
            security: []
            description: Delete home data
            tags:
                - home
            summary: Delete
            operationId: DeleteHome
    /v1/route:
        get:
            parameters:
                - required: true
                  minItems: !!float 2
                  uniqueItems: true
                  type: array
                  items:
                    type: number
                    format: uint64
                  name: home_ids
                  in: query
            responses:
                "200":
                    description: Success get data
                    schema:
                        $ref: '#/definitions/successFindRoute'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Find route between 2 homes or more
            tags:
                - route
            summary: Find Route
            operationId: FindRoute
definitions:
    successFindAllPagination:
        allOf:
            - $ref: '#/definitions/successCreateAllOf0'
            - $ref: '#/definitions/successFindAllPaginationAllOf1'
    successFindOneAllOf1:
        type: object
        properties:
            data:
                $ref: '#/definitions/successFindOneAllOf1Data'
        x-go-gen-location: models
    successFindRouteAllOf1:
        type: object
        properties:
            data:
                type: array
                items:
                    $ref: '#/definitions/successFindRouteAllOf1DataItems'
        x-go-gen-location: models
    Home:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/homeData'
            - $ref: '#/definitions/modelTrackTime'
    createHomeParamsBody:
        type: object
        required:
            - type
            - address
        properties:
            address:
                type: string
            type:
                type: number
                format: int
                enum:
                    - !!float 36
                    - !!float 45
                    - !!float 72
        x-go-gen-location: operations
    homeWithoutTrackTime:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/homeData'
    metadata:
        type: object
        properties:
            page:
                type: integer
            per_page:
                type: integer
            total_page:
                type: integer
            total_row:
                type: integer
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    successCreate:
        allOf:
            - $ref: '#/definitions/successCreateAllOf0'
            - $ref: '#/definitions/successCreateAllOf1'
    successFindAllPaginationAllOf1:
        type: object
        properties:
            data:
                type: array
                items:
                    $ref: '#/definitions/successFindOneAllOf1Data'
            metadata:
                $ref: '#/definitions/successFindAllPaginationAllOf1Metadata'
        x-go-gen-location: models
    successFindAllPaginationAllOf1Metadata:
        allOf:
            - $ref: '#/definitions/metadata'
            - $ref: '#/definitions/customFields'
        x-go-gen-location: models
    customFields:
        type: object
        additionalProperties:
            type: object
        x-go-package: time
    error:
        properties:
            code:
                type: integer
            message:
                type: string
                example: error
        type: object
    updateHomeParamsBody:
        type: object
        required:
            - type
            - address
        properties:
            address:
                type: string
            type:
                type: number
                format: int
                enum:
                    - !!float 36
                    - !!float 45
                    - !!float 72
        x-go-gen-location: operations
    successCreateAllOf0:
        type: object
        properties:
            message:
                type: string
        x-go-gen-location: models
    successCreateAllOf1:
        type: object
        properties:
            home_id:
                type: number
                format: uint64
        x-go-gen-location: models
    successFindRouteAllOf1DataItems:
        x-go-gen-location: models
        type: object
        properties:
            destination:
                $ref: '#/definitions/homeWithoutTrackTime'
            distance:
                format: float64
                x-omitempty: false
                description: distance in meters
                type: number
            origin:
                $ref: '#/definitions/homeWithoutTrackTime'
    modelTrackTime:
        type: object
        properties:
            created_at:
                type: string
                format: date-time
                x-nullable: true
                x-omitempty: false
            deleted_at:
                type: string
                format: date-time
                x-nullable: true
                x-omitempty: false
            updated_at:
                format: date-time
                x-nullable: true
                x-omitempty: false
                type: string
    success:
        properties:
            message:
                type: string
        type: object
    successFindOneAllOf1Data:
        x-go-gen-location: models
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/homeData'
            - $ref: '#/definitions/modelTrackTime'
    successFindRoute:
        allOf:
            - $ref: '#/definitions/successCreateAllOf0'
            - $ref: '#/definitions/successFindRouteAllOf1'
    homeData:
        type: object
        properties:
            address_line:
                type: string
            country:
                type: string
            latitude:
                type: number
            subdistrict:
                type: string
            address:
                type: string
            formatted_address:
                type: string
            longitude:
                type: number
            postal_code:
                type: string
            regency:
                type: string
            type:
                type: string
    successFindOne:
        allOf:
            - $ref: '#/definitions/successCreateAllOf0'
            - $ref: '#/definitions/successFindOneAllOf1'
securityDefinitions:
    authorization:
        type: apiKey
        name: Authorization
        in: header
