consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: Test Biofarma
    version: 1.0.0
paths:
    /health:
        get:
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                "200":
                    schema:
                        $ref: '#/definitions/success'
                    description: Health Check
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
    /v1/home:
        post:
            operationId: createHome
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createHomeParamsBody'
            responses:
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreate'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security: []
            description: Create new home data
            tags:
                - home
            summary: Create
    /v1/home/{home_id}:
        get:
            responses:
                "200":
                    description: Success get data
                    schema:
                        $ref: '#/definitions/successFindOne'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Find one home data
            tags:
                - home
            summary: Find One
            operationId: FindOneHome
            parameters:
                - type: integer
                  format: uint64
                  name: home_id
                  in: path
                  required: true
                - default: "false"
                  description: flag for identify include deleted data or not
                  name: include_deleted_data
                  in: query
                  enum:
                    - "true"
                    - "false"
                  type: string
        put:
            security: []
            description: Update home data
            tags:
                - home
            summary: Update
            operationId: UpdateHome
            parameters:
                - required: true
                  type: integer
                  format: uint64
                  name: home_id
                  in: path
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/updateHomeParamsBody'
            responses:
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
                "200":
                    schema:
                        $ref: '#/definitions/success'
                    description: Success update
        delete:
            security: []
            description: Delete home data
            tags:
                - home
            summary: Delete
            operationId: DeleteHome
            parameters:
                - type: integer
                  format: uint64
                  name: home_id
                  in: path
                  required: true
            responses:
                "200":
                    description: Success delete data
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
definitions:
    homeData:
        type: object
        properties:
            address:
                type: string
            latitude:
                type: number
            longitude:
                type: number
            type:
                type: string
            address_line:
                type: string
            country:
                type: string
            formatted_address:
                type: string
            postal_code:
                type: string
            regency:
                type: string
            subdistrict:
                type: string
    successCreateAllOf0:
        properties:
            message:
                type: string
        x-go-gen-location: models
        type: object
    successCreate:
        allOf:
            - $ref: '#/definitions/successCreateAllOf0'
            - $ref: '#/definitions/successCreateAllOf1'
    successCreateAllOf1:
        type: object
        properties:
            home_id:
                type: number
                format: uint64
        x-go-gen-location: models
    successFindOne:
        allOf:
            - $ref: '#/definitions/successCreateAllOf0'
            - $ref: '#/definitions/successFindOneAllOf1'
    updateHomeParamsBody:
        type: object
        required:
            - type
            - address
        properties:
            address:
                type: string
            type:
                enum:
                    - !!float 36
                    - !!float 45
                    - !!float 72
                type: number
                format: int
        x-go-gen-location: operations
    Home:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/homeData'
            - $ref: '#/definitions/modelTrackTime'
    error:
        type: object
        properties:
            code:
                type: integer
            message:
                example: error
                type: string
    modelTrackTime:
        type: object
        properties:
            created_at:
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
                x-nullable: true
                x-omitempty: false
                type: string
            deleted_at:
                format: date-time
                x-go-custom-tag: gorm:"deleted_at"
                x-nullable: true
                x-omitempty: false
                type: string
            updated_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:updated_at"
                x-nullable: true
                x-omitempty: false
    createHomeParamsBody:
        x-go-gen-location: operations
        type: object
        required:
            - type
            - address
        properties:
            address:
                type: string
            type:
                type: number
                format: int
                enum:
                    - !!float 36
                    - !!float 45
                    - !!float 72
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    successFindOneAllOf1:
        type: object
        properties:
            data:
                $ref: '#/definitions/successFindOneAllOf1Data'
        x-go-gen-location: models
    success:
        type: object
        properties:
            message:
                type: string
    successFindOneAllOf1Data:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/homeData'
            - $ref: '#/definitions/modelTrackTime'
        x-go-gen-location: models
securityDefinitions:
    authorization:
        type: apiKey
        name: Authorization
        in: header
