consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    version: 1.0.0
    title: Test Biofarma
paths:
    /health:
        get:
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
    /v1/home:
        post:
            description: Create new home data
            tags:
                - home
            summary: Create
            operationId: createHome
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createHomeParamsBody'
            responses:
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreate'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security: []
    /v1/home/{home_id}:
        put:
            summary: Update
            operationId: UpdateHome
            parameters:
                - format: uint64
                  name: home_id
                  in: path
                  required: true
                  type: integer
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/updateHomeParamsBody'
            responses:
                "200":
                    description: Success update
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Update home data
            tags:
                - home
definitions:
    Home:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/homeData'
    createHomeParamsBody:
        type: object
        required:
            - type
            - address
        properties:
            address:
                type: string
            type:
                format: int
                enum:
                    - !!float 36
                    - !!float 45
                    - !!float 72
                type: number
        x-go-gen-location: operations
    error:
        properties:
            code:
                type: integer
            message:
                type: string
                example: error
        type: object
    homeData:
        type: object
        properties:
            postal_code:
                type: string
            subdistrict:
                type: string
            type:
                type: string
            address_line:
                type: string
            formatted_address:
                type: string
            latitude:
                type: number
            longitude:
                type: number
            regency:
                type: string
            address:
                type: string
            country:
                type: string
    successCreate:
        allOf:
            - $ref: '#/definitions/successCreateAllOf0'
            - $ref: '#/definitions/successCreateAllOf1'
    successCreateAllOf0:
        type: object
        properties:
            message:
                type: string
        x-go-gen-location: models
    updateHomeParamsBody:
        type: object
        required:
            - type
            - address
        properties:
            type:
                format: int
                enum:
                    - !!float 36
                    - !!float 45
                    - !!float 72
                type: number
            address:
                type: string
        x-go-gen-location: operations
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    modelTrackTime:
        properties:
            created_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
                x-nullable: true
                x-omitempty: false
            deleted_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:deleted_at"
                x-nullable: true
                x-omitempty: false
            updated_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:updated_at"
                x-nullable: true
                x-omitempty: false
        type: object
    success:
        type: object
        properties:
            message:
                type: string
    successCreateAllOf1:
        type: object
        properties:
            home_id:
                type: number
                format: uint64
        x-go-gen-location: models
securityDefinitions:
    authorization:
        type: apiKey
        name: Authorization
        in: header
